// Gas defines because i hate typepaths
#define GAS_O2					"o2"
#define GAS_N2					"n2"
#define GAS_CO2					"co2"
#define GAS_PLASMA				"plasma"
#define GAS_H2O					"water_vapor"
#define GAS_HYPERNOB			"nob"
#define GAS_NITROUS				"n2o"
#define GAS_NITRYL				"no2"
#define GAS_TRITIUM				"tritium"
#define GAS_BZ					"bz"
#define GAS_STIMULUM			"stim"
#define GAS_PLUOXIUM			"pluox"
#define GAS_MIASMA				"miasma"
#define GAS_FREON				"freon"
#define GAS_HEALIUM				"healium"
#define GAS_PROTO_NITRATE		"proto_nitrate"
#define GAS_ZAUKER				"zauker"
#define GAS_HALON				"halon"
#define GAS_HELIUM				"helium"
#define GAS_ANTINOBLIUM			"antinoblium"
#define GAS_HYDROGEN			"hydrogen"

#define GAS_FLAG_DANGEROUS		(1<<0)
#define GAS_FLAG_BREATH_PROC	(1<<1)
